# Generated by Django 4.1.7 on 2023-03-12 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[['G', 'Gasoline'], ['D', 'Diesel'], ['BD', 'Bio-Diesel'], ['E', 'Ethanol']], max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission_type',
            field=models.CharField(choices=[['M', 'Manual'], ['A', 'Automatic'], ['C', 'CVT']], max_length=200),
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(choices=[['M', 'Male'], ['F', 'Female'], ['D', 'Disabled'], ['N', 'Do not want to answer']], max_length=20)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='application.car')),
            ],
        ),
    ]
