# Generated by Django 4.1.7 on 2023-03-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_alter_car_fuel_type_alter_car_transmission_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_person', models.CharField(blank=True, max_length=100)),
                ('fee', models.IntegerField(blank=True)),
                ('date', models.DateField()),
                ('pickup', models.BooleanField()),
                ('details', models.TextField(max_length=300)),
            ],
        ),
    ]
