# Generated by Django 4.1.7 on 2023-03-18 12:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='buyer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='application.buyer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery',
            name='car',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='application.car'),
            preserve_default=False,
        ),
    ]
