# Generated by Django 4.1.7 on 2023-03-18 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_delivery_buyer_delivery_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='car',
        ),
    ]
