# Generated by Django 4.1.7 on 2023-03-18 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_delivery_buyer_delivery_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_person', models.CharField(blank=True, max_length=100)),
                ('fee', models.IntegerField(blank=True)),
                ('date', models.DateField()),
                ('pickup', models.BooleanField()),
                ('details', models.TextField(max_length=300)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='application.buyer')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='application.car')),
            ],
        ),
        migrations.DeleteModel(
            name='Delivery',
        ),
    ]
