# Generated by Django 4.1.7 on 2023-03-18 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_deliveryservice_delete_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[['G', 'Gasoline'], ['D', 'Diesel'], ['BD', 'Bio-Diesel'], ['E', 'Electric']], max_length=200),
        ),
    ]
