# Generated by Django 4.1.7 on 2023-03-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_alter_car_fuel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='cc',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
