# Generated by Django 4.1.7 on 2023-03-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_alter_car_cc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryservice',
            name='details',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='deliveryservice',
            name='fee',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
