# Generated by Django 4.2 on 2023-04-23 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_alter_deliveryservice_details_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('owner', models.CharField(blank=True, max_length=100)),
                ('number_of_employees', models.IntegerField(blank=True, default=1)),
            ],
        ),
    ]
